### ISSUE TITLE
invalid number of arguments

### ISSUE THREAD

**Issue by qinhui99** [PavelOstyakov/toxic#1]
Epoch 11 loss 0.04497938698477566 best_loss 0.0413083174741875
Predicting results...
Traceback (most recent call last):
  File "fit_predict.py", line 124, in <module>
    main()
  File "fit_predict.py", line 110, in main
    test_predicts = np.multiply(*test_predicts_list)
ValueError: invalid number of arguments.

Did I miss something?

**Comment by PavelOstyakov** [comment]
I checked it on the newest numpy version (1.14). It seems that they changed the function because this code works with numpy 1.13. Thank you, I'll upload a fix
